% Test script for runNaturalImageExperiment function
% 
% The options are defined below:
% 'directoryName' : Name of directory where the LMS struct and the trialStruct is stored
% 'nameOfTrialStruct' : Name of trial struct that will be used in the experiment
% 'controlSignal' : The input method for response 'keyboard' or 'gamePad'
% 'interval1Key' : For keyboard -> '1', For gamePad either 'GP:1' or 'GP:X'
% 'interval2Key' : For keyboard -> '2', For gamePad either 'GP:2' or 'GP:A'
% 'feedback' : Give feedback if option is on
% 'subjectName' : Name of the subject

runNaturalImageExperiment('directoryName', 'ExampleCase',...
        'nameOfTrialStruct', 'exampleTrial', ...
        'nameOfCalibrationFile', 'VirtualWorldCalibration.mat', ...
        'controlSignal', 'keyboard', ...
        'interval1Key', '1', ...
        'interval2Key', '2', ...  
        'feedback', 1, ...
        'isDemo', 1, ... %data won't be saved
        'subjectName', 'testSubject', ...
        'theoreticalPsychophysicsMode', 0);
    
% mglClose;  ListenChar(0);